### ISSUE TITLE
List Java as a build/test requirement.

### ISSUE THREAD

**Issue by simar7** [mozilla/mozmill-ci#546]
Currently in the [Installation docs] (https://github.com/mozilla/mozmill-ci/wiki/Installation), we don't specify Java as a pre-requisite or a requirement.

A beginner, might stumble upon such an issue: http://pastebin.mozilla.org/8364216

Possible ideas:
* We should either list Java as a pre-requisite.
* Install it as part of the setup.sh script.

I vote for listing it as a pre-requisite given the nature and size of the package before a contributor fully commits to working on mozmill-ci.

**Comment by whimboo** [comment]
Interesting. It looks like this part was missed to be added to the wiki page when I did the documentation refactoring in October last year. Maybe the best here would be to add another line to the installation instructions in the wiki. A link to the following URL might be helpful for Ubuntu users:

http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html

Otherwise the packages should be downloaded from java.com.

**Comment by simar7** [comment]
This has been taken care of. Closing.

**Comment by whimboo** [comment]
Thanks!
