### ISSUE TITLE
inapproriate usercancel results: m-c win8 opt Fxfn en-US

### ISSUE THREAD

**Issue by mjzffr** [mozilla/mozmill-ci#747]
I'm seeing persistent usercancel results on Windows 8 Fxfn. Example: http://mm-ci-production.qa.scl3.mozilla.com:8080/job/mozilla-central_functional/2236/

**Comment by whimboo** [comment]
You should not reference jobs in Jenkins given that those are getting deleted after a 3 days. It's better to list the appropriate Treeherder jobs. I will have a look if I can find something.

**Comment by mjzffr** [comment]
https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&filter-searchStr=firefox%20ui&filter-tier=1&filter-tier=2&filter-tier=3&selectedJob=3325714

**Comment by whimboo** [comment]
Thanks Maja but that one doesn't exist neither. But there is a job from late Friday where we still have a Jenkins log:

https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&filter-searchStr=firefox%20ui&filter-tier=1&filter-tier=2&filter-tier=3&selectedJob=3332816

http://mm-ci-production.qa.scl3.mozilla.com:8080/job/mozilla-central_functional/2260/console

So the reason here is that the workspace cannot be deleted at the beginning of the Jenkins job. Because of that we do not send a `running` state but a `completed` immediately. With that we activate the virtualenv as created by the former job on this machine, and read the exit code 6.

> Read build exit code: 6 (usercancel)

Looks like issue #720 didn't fix it for all cases.

**Comment by whimboo** [comment]
Hm, looks like we did this on purpose:

https://github.com/mozilla/mozmill-ci/blob/master/jenkins-master/jobs/scripts/workspace/submission.py#L362

So we have two situations here...

1) The user cancels a job before an exit code is available. That should result in usercancel.
2) A failure like issue #358 can cause an early abort. That should result in an aborted job.

2) would behave similar to 1) inside of Jenkins. In both cases our submission script will be called via the postbuild action. It won't be able to determine the difference.

I do not see any environment variable used by Jenkins for the current build status. That means it might be kinda hard to check for that difference. Because of that and that we want to get rid of mozmill-ci in the next months, shall we simply set the result to `busted`?

@mjzffr and @sydvicious what do you think?

**Comment by mjzffr** [comment]
I think 'busted' is ok. You could add a log message to warn/remind people
of this unclear case and help distinguish from normal bustage.

Maja Frydrychowicz
irc: maja_zf

**Comment by whimboo** [comment]
I don't think that this will help at the moment to add a log entry given that we can only submit the log from the mozharness run. The necessary logging here would be outside of it.

**Comment by whimboo** [comment]
PR #749 has been merged.
